---
abstract: 'HTML::MobileJp plugin for Template-Toolkit'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-HTMLMobileJp
no_index:
  directory:
    - inc
    - t
provides:
  Template::Plugin::HTMLMobileJp:
    file: lib/Template/Plugin/HTMLMobileJp.pm
    version: 0.02
requires:
  Filter::Util::Call: 0
  HTML::MobileJp: 0
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
